# Generated by Django 5.0.6 on 2024-05-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="projects/")),
                ("demo_link", models.URLField(blank=True)),
                ("source_code_link", models.URLField(blank=True)),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
