# Generated by Django 5.0.6 on 2024-05-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_service_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
        migrations.AddField(
            model_name="skill",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="skills/"),
        ),
    ]
