# Generated by Django 5.0.6 on 2024-05-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("url", models.URLField()),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Enter the CSS class for the icon (e.g., 'fab fa-twitter')",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
