# Generated by Django 5.0.6 on 2024-05-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_sociallink"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
