# Generated by Django 5.0.6 on 2024-05-27 18:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
